import type { Metadata } from "next";
import { Geist, Geist_Mono, Germania_One } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const germania = Germania_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-germania",
});

export const metadata: Metadata = {
  title: "Ok'Rhams Homepage",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${germania.variable} antialiased`}
      >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
